import { format } from 'date-fns'
import { Download, FileUp, RotateCcw } from 'lucide-react'
import { useState, type ChangeEvent } from 'react'
import { useAppData } from '../../hooks/useAppData'
import { useToast } from '../../hooks/useToast'
import { ConfirmDialog } from '../common/ConfirmDialog'

export function SettingsPanel() {
  const { data, resetDemoData, replaceData } = useAppData()
  const { showToast } = useToast()
  const [pendingReset, setPendingReset] = useState(false)
  const exportData = () => { const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `habittrack-backup-${format(new Date(), 'yyyy-MM-dd')}.json`; link.click(); URL.revokeObjectURL(url); showToast('Backup exported.') }
  const importData = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { try { const valid = replaceData(JSON.parse(String(reader.result))); showToast(valid ? 'Backup restored.' : 'Invalid HabitTrack backup.', valid ? 'success' : 'error') } catch { showToast('The file is not valid JSON.', 'error') } event.target.value = '' }; reader.readAsText(file) }
  const confirmReset = () => { resetDemoData(); setPendingReset(false); showToast('Demo data restored.', 'info') }
  return <section className="mt-6 space-y-4"><div className="rounded-3xl border border-[var(--border)] bg-[var(--panel)] p-5 shadow-[var(--shadow)] sm:p-6"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[var(--accent)]">Data portability</p><h2 className="mt-1 text-xl font-semibold text-[var(--text-strong)]">Backups and local data</h2><p className="mt-2 text-sm leading-6 text-[var(--text-muted)]">Export your raw workspace as JSON or restore a validated backup.</p><div className="mt-5 flex flex-wrap gap-3"><button className="inline-flex items-center gap-2 rounded-xl bg-[var(--accent)] px-4 py-2.5 text-sm font-bold text-slate-950" type="button" onClick={exportData}><Download size={17} /> Export data</button><label className="inline-flex cursor-pointer items-center gap-2 rounded-xl border border-[var(--border-strong)] px-4 py-2.5 text-sm font-semibold text-[var(--text-strong)]"><FileUp size={17} /> Import data<input className="sr-only" type="file" accept="application/json,.json" onChange={importData} /></label><button className="inline-flex items-center gap-2 rounded-xl border border-rose-400/30 px-4 py-2.5 text-sm font-semibold text-rose-400" type="button" onClick={() => setPendingReset(true)}><RotateCcw size={17} /> Reset demo data</button></div></div><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-2xl border border-[var(--border)] bg-[var(--panel-soft)] p-5"><p className="text-xs uppercase tracking-[0.12em] text-[var(--text-faint)]">Theme</p><p className="mt-3 text-sm font-semibold text-[var(--text-strong)]">Use the header toggle to switch dark and light mode.</p></div><div className="rounded-2xl border border-[var(--border)] bg-[var(--panel-soft)] p-5"><p className="text-xs uppercase tracking-[0.12em] text-[var(--text-faint)]">Currency</p><p className="mt-3 text-sm font-semibold text-[var(--text-strong)]">Indian Rupee (INR)</p></div></div>{pendingReset ? <ConfirmDialog title="Reset demo data?" message="This replaces your local workspace with the original sample data." confirmLabel="Reset data" onCancel={() => setPendingReset(false)} onConfirm={confirmReset} /> : null}</section>
}