import { addYears } from 'date-fns'
import { ChevronLeft, ChevronRight, CircleDollarSign } from 'lucide-react'
import { useAppData } from '../../hooks/useAppData'
import { calculateYearlyOverview } from '../../utils/yearlyCalculations'
import { formatINR } from '../../utils/expenseCalculations'

export function YearlyOverview({ month, onSelectMonth }: { month: Date; onSelectMonth: (month: Date) => void }) {
  const { data } = useAppData()
  const year = month.getFullYear()
  const overview = calculateYearlyOverview(data.habits, data.habitLogs, data.expenses, year)

  return <div className="mt-6 space-y-6"><section className="rounded-3xl border border-[var(--border)] bg-[var(--panel)] p-5 shadow-[var(--shadow)] sm:p-6"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[var(--accent)]">Year in review</p><h2 className="mt-1 text-xl font-semibold text-[var(--text-strong)]">{year} overview</h2></div><div className="flex items-center gap-1"><button className="date-button border border-[var(--border)]" type="button" onClick={() => onSelectMonth(addYears(month, -1))} aria-label="Previous year"><ChevronLeft size={16} /></button><button className="date-button border border-[var(--border)]" type="button" onClick={() => onSelectMonth(addYears(month, 1))} aria-label="Next year"><ChevronRight size={16} /></button></div></div><div className="mt-6 grid gap-4 sm:grid-cols-4"><YearStat label="Completed" value={String(overview.completed)} /><YearStat label="Goal" value={String(overview.goal)} /><YearStat label="Progress" value={`${overview.percentage}%`} /><YearStat label="Expenses" value={formatINR(overview.expenses)} /></div></section><section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{overview.summaries.map((summary) => <button className="group rounded-2xl border border-[var(--border)] bg-[var(--panel)] p-5 text-left transition hover:-translate-y-0.5 hover:border-[var(--accent-border)]" type="button" key={summary.label} onClick={() => onSelectMonth(summary.month)}><div className="flex items-start justify-between"><div><p className="text-lg font-semibold text-[var(--text-strong)]">{summary.label}</p><p className="mt-1 text-xs text-[var(--text-muted)]">Open monthly dashboard</p></div><CircleDollarSign className="text-[var(--text-faint)] transition group-hover:text-[var(--accent)]" size={18} /></div><div className="mt-5 grid grid-cols-3 gap-2"><div><p className="text-lg font-semibold text-[var(--text-strong)]">{summary.completed}</p><p className="text-[10px] uppercase tracking-wide text-[var(--text-faint)]">Done</p></div><div><p className="text-lg font-semibold text-[var(--text-strong)]">{summary.goal}</p><p className="text-[10px] uppercase tracking-wide text-[var(--text-faint)]">Goal</p></div><div><p className="text-lg font-semibold text-[var(--accent)]">{summary.percentage}%</p><p className="text-[10px] uppercase tracking-wide text-[var(--text-faint)]">Progress</p></div></div><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-[var(--track)]"><div className="h-full rounded-full bg-[var(--accent)]" style={{ width: `${summary.percentage}%` }} /></div><p className="mt-3 text-xs text-[var(--text-muted)]">{formatINR(summary.expenses)} spent</p></button>)}</section></div>
}

function YearStat({ label, value }: { label: string; value: string }) {
  return <div className="rounded-2xl border border-[var(--border)] bg-[var(--panel-soft)] p-4"><p className="text-xs uppercase tracking-[0.12em] text-[var(--text-faint)]">{label}</p><p className="mt-3 text-2xl font-semibold text-[var(--text-strong)]">{value}</p></div>
}