import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { useAppData } from '../../hooks/useAppData'
import { calculateExpenseAnalytics, formatINR } from '../../utils/expenseCalculations'

const chartTooltipStyle = { background: '#102238', border: '1px solid #2b4662', borderRadius: 12, color: '#f8fafc' }

export function ExpenseOverview({ month }: { month: Date }) {
  const { data } = useAppData()
  const analytics = calculateExpenseAnalytics(data.expenses, month)

  return <div className="mt-6 space-y-6">
    <div className="grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border border-[var(--border)] bg-[var(--panel-soft)] p-5"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-[var(--text-faint)]">Monthly expenses</p><p className="mt-4 text-2xl font-semibold text-[var(--text-strong)]">{formatINR(analytics.total)}</p><p className="mt-1 text-xs text-[var(--text-muted)]">{analytics.monthExpenses.length} recorded items</p></div><div className="rounded-2xl border border-[var(--border)] bg-[var(--panel-soft)] p-5"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-[var(--text-faint)]">Highest category</p><p className="mt-4 text-2xl font-semibold text-[var(--text-strong)]">{analytics.categories[0]?.category ?? 'None'}</p><p className="mt-1 text-xs text-[var(--text-muted)]">{analytics.categories[0] ? formatINR(analytics.categories[0].amount) : 'Start tracking your spending'}</p></div><div className="rounded-2xl border border-[var(--border)] bg-[var(--panel-soft)] p-5"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-[var(--text-faint)]">Average per day</p><p className="mt-4 text-2xl font-semibold text-[var(--text-strong)]">{formatINR(analytics.daily.length ? analytics.total / analytics.daily.length : 0)}</p><p className="mt-1 text-xs text-[var(--text-muted)]">across the full month</p></div></div>
    <div className="grid gap-6 xl:grid-cols-[1.35fr_0.65fr]"><section className="min-w-0 rounded-3xl border border-[var(--border)] bg-[var(--panel)] p-5 shadow-[var(--shadow)] sm:p-6"><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-emerald-400">Spending rhythm</p><h2 className="mt-1 text-lg font-semibold text-[var(--text-strong)]">Daily expenses</h2><div className="mt-5 h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={analytics.daily} margin={{ top: 5, right: 5, bottom: 0, left: 10 }}><CartesianGrid vertical={false} stroke="var(--border)" strokeDasharray="4 4" /><XAxis dataKey="day" tick={{ fill: '#91a4b9', fontSize: 11 }} tickLine={false} axisLine={false} /><YAxis tick={{ fill: '#91a4b9', fontSize: 11 }} tickLine={false} axisLine={false} width={48} /><Tooltip contentStyle={chartTooltipStyle} formatter={(value) => [formatINR(Number(value)), 'Spent']} labelFormatter={(label) => `September ${label}`} /><Bar dataKey="amount" fill="#65d39b" radius={[5, 5, 0, 0]} maxBarSize={18} /></BarChart></ResponsiveContainer></div></section><section className="rounded-3xl border border-[var(--border)] bg-[var(--panel)] p-5 shadow-[var(--shadow)] sm:p-6"><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-emerald-400">Weekly view</p><h2 className="mt-1 text-lg font-semibold text-[var(--text-strong)]">Weekly totals</h2><div className="mt-5 space-y-3">{analytics.weekly.map((week, index) => <div className="flex items-center justify-between rounded-xl border border-[var(--border)] bg-[var(--panel-soft)] p-3" key={week.label}><div><p className="text-sm font-semibold text-[var(--text-strong)]">Week {index + 1}</p><p className="text-xs text-[var(--text-muted)]">{week.label} September</p></div><p className="text-sm font-bold text-emerald-400">{formatINR(week.amount)}</p></div>)}</div></section></div>
  </div>
}